/* TinyCBOR version header, normally generated by its CMake (lib/lionkey/lib/tinycbor). */
#define TINYCBOR_VERSION_MAJOR      7
#define TINYCBOR_VERSION_MINOR      0
#define TINYCBOR_VERSION_PATCH      0
