"""Generate the list of all eFuse fields from ESP-IDF's esp_efuse_table.csv.

Output: one `EFUSE_FIELD(name, ESP_EFUSE_<ident>, block, "comment")` line per
named field, so the firmware can dump every eFuse without a hand-kept list.
Usage: gen_efuse_fields.py <esp_efuse_table.csv> <output.inc>
"""

import re
import sys


def main(csv_path: str, out_path: str) -> None:
    lines = []
    with open(csv_path, encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = [p.strip() for p in line.split(",", 4)]
            name = parts[0]
            if not name:  # continuation of a multi-part field (e.g. MAC)
                continue
            block = parts[1].replace("EFUSE_BLK", "")
            comment = parts[4] if len(parts) > 4 else ""
            comment = re.sub(r"^\[[^\]]*\]\s*", "", comment)  # drop alias list
            comment = comment.replace("\\", "\\\\").replace('"', "'")
            ident = "ESP_EFUSE_" + name.replace(".", "_")
            lines.append(f'EFUSE_FIELD("{name}", {ident}, {block}, "{comment}")\n')

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by gen_efuse_fields.py, do not edit.\n")
        f.writelines(lines)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
